# Generated by Django 5.1.15 on 2026-06-13 17:40

import django.db.models.deletion
from django.conf import settings

# ruff: noqa: E501
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estimates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Nome descritivo dado pelo usuário a este histórico.', max_length=300, verbose_name='Título')),
                ('notes', models.TextField(blank=True, default='', help_text='Anotações livres do usuário sobre esta estimativa.', verbose_name='Observações')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_histories', to='estimates.energyestimate', verbose_name='Estimativa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_histories', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Histórico de Geração',
                'verbose_name_plural': 'Históricos de Geração',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('csv', 'CSV'), ('pdf', 'PDF')], default='csv', help_text='Formato do arquivo exportado: csv ou pdf.', max_length=10, verbose_name='Formato')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Gerado em')),
                ('file_name', models.CharField(blank=True, help_text='Nome do arquivo gerado (sem caminho). Vazio enquanto pendente.', max_length=300, verbose_name='Nome do Arquivo')),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_exports', to='estimates.energyestimate', verbose_name='Estimativa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_exports', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Exportação de Relatório',
                'verbose_name_plural': 'Exportações de Relatório',
                'ordering': ['-generated_at'],
            },
        ),
    ]
