# Generated by Django 5.1.15 on 2026-06-13 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_kwh', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Energia Diária (kWh)')),
                ('monthly_kwh', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Energia Mensal (kWh)')),
                ('yearly_kwh', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Energia Anual (kWh)')),
                ('efficiency_index', models.DecimalField(decimal_places=4, help_text='Performance Ratio do sistema fotovoltaico.', max_digits=8, verbose_name='Índice de Eficiência (PR)')),
                ('losses_factor', models.DecimalField(decimal_places=2, default=0.8, help_text='Fração de energia aproveitada após perdas sistêmicas (0.0–1.0). Padrão: 0.80.', max_digits=4, verbose_name='Fator de Perdas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('module', models.ForeignKey(help_text='Painel solar utilizado no cálculo. Preservado mesmo se o módulo for excluído.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='energy_estimates', to='core.solarmodule', verbose_name='Módulo Solar')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='energy_estimates', to='core.region', verbose_name='Região')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='energy_estimates', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Estimativa de Energia',
                'verbose_name_plural': 'Estimativas de Energia',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeatherSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Data à qual o snapshot se refere (YYYY-MM-DD).', verbose_name='Data')),
                ('irradiation', models.DecimalField(decimal_places=3, help_text='Irradiação solar global horizontal média do dia.', max_digits=7, null=True, verbose_name='Irradiação (kWh/m²/dia)')),
                ('temperature', models.DecimalField(decimal_places=2, help_text='Temperatura média do ar em graus Celsius.', max_digits=5, null=True, verbose_name='Temperatura (°C)')),
                ('cloud_cover', models.DecimalField(decimal_places=2, help_text='Percentual médio de cobertura de nuvens no dia.', max_digits=5, null=True, verbose_name='Cobertura de Nuvens (%)')),
                ('source', models.CharField(default='open-meteo', help_text='Identificador da fonte dos dados climáticos.', max_length=100, verbose_name='Fonte')),
                ('raw_json', models.JSONField(blank=True, help_text='Resposta bruta da API para fins de auditoria e debug.', null=True, verbose_name='JSON Bruto')),
                ('status', models.CharField(choices=[('ok', 'OK'), ('error', 'Erro'), ('cached', 'Cacheado')], default='ok', help_text='Qualidade/origem do dado: ok, error ou cached.', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_snapshots', to='core.region', verbose_name='Região')),
            ],
            options={
                'verbose_name': 'Snapshot Climático',
                'verbose_name_plural': 'Snapshots Climáticos',
                'ordering': ['-date'],
                'unique_together': {('region', 'date')},
            },
        ),
    ]
