# Generated by Django 6.0.4 on 2026-06-17 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='energyestimate',
            name='weather_snapshot',
            field=models.ForeignKey(blank=True, help_text='Snapshot climático utilizado no cálculo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='energy_estimates', to='estimates.weathersnapshot', verbose_name='Snapshot Climático'),
        ),
    ]
