# Generated by Django 5.1.15 on 2026-06-13 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome do município ou localidade.', max_length=200, verbose_name='Nome')),
                ('state', models.CharField(help_text='Sigla do estado, ex: "RN".', max_length=2, verbose_name='UF')),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Latitude em graus decimais (WGS 84).', max_digits=9, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Longitude em graus decimais (WGS 84).', max_digits=9, verbose_name='Longitude')),
                ('source', models.CharField(default='seed', help_text='"seed" para regiões do fixture inicial; "user" para registros manuais.', max_length=100, verbose_name='Fonte')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Região',
                'verbose_name_plural': 'Regiões',
                'ordering': ['state', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SolarModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(help_text='Identificação comercial do painel (ex: "RS-540M10").', max_length=200, verbose_name='Modelo')),
                ('manufacturer', models.CharField(help_text='Nome do fabricante (ex: "Canadian Solar").', max_length=200, verbose_name='Fabricante')),
                ('power_wp', models.DecimalField(decimal_places=2, help_text='Potência de pico em Watts-pico.', max_digits=8, verbose_name='Potência (Wp)')),
                ('efficiency', models.DecimalField(decimal_places=2, help_text='Eficiência de conversão fotovoltaica em percentual.', max_digits=5, verbose_name='Eficiência (%)')),
                ('area_m2', models.DecimalField(decimal_places=3, help_text='Área total do painel em metros quadrados.', max_digits=6, verbose_name='Área (m²)')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Número de painéis no conjunto.', verbose_name='Quantidade')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solar_modules', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Módulo Solar',
                'verbose_name_plural': 'Módulos Solares',
                'ordering': ['-created_at'],
            },
        ),
    ]
