    @startuml "heliometrica"
    skinparam classAttributeIconSize 0
    left to right direction

    class Usuario{
        - nome: String
        - email: String
        - senha: String
        + autenticar(): boolean
        + atualizar_cadastro(): void
        + gerenciar_historico(): void
    }

    class ModuloSolar{
        - modelo: String
        - potencia: Double
        - eficiencia: Double
        - area: Double
        - fabricante: String
        + cadastrar_especificacoes(): void
        + editar_especificacoes(): void
    }

    class HistoricoGeracao{
        - lista_estimativas: List<EstimativaEnergetica>
        - data_atualizacao: Date
        + salvar(estimativa: EstimativaEnergetica): void
        + editar(estimativa: EstimativaEnergetica): void
        + excluir(id: String): void
        + listar(): List<EstimativaEnergetica>
    }

    class EstimativaEnergetica{
        - valor_estimado: Double
        - data_calculo: Date
        - eficiencia_calculada: Double
        + calcular_estimativa(modulo: ModuloSolar, regiao: Regiao): Double
    }

    class Relatorio{
        - tipo_formato: String
        - data_exportacao: Date
        - conteudo: String
        + exportar(): Boolean
    }

    class Regiao{
        - nome: String
        - coordenadas: String
        - eficiencia_energetica: Double
        - historico_meteorologico: String
        + visualizar_eficiencia(): Double
    }

    class APIClima{
        + buscar_dados_meteorologicos(regiao: Regiao): String   
    }

    Usuario "1" -down-* "0..1" HistoricoGeracao: possui >
    Usuario "1" -right- "0..*" ModuloSolar: cadastra >

    HistoricoGeracao "1" o-down- "0..*" EstimativaEnergetica: armazena >
    ModuloSolar "1" -down- "0..*" EstimativaEnergetica: usado >

    EstimativaEnergetica "1" -down- "1" Regiao: utiliza >
    Relatorio "0..*" o-left- "1..*" EstimativaEnergetica: exporta >

    Regiao -right-> APIClima: consulta >

    @enduml